const APP_VERSION='5.0.1';
state.meta??={};state.meta.v5DemoCleaned=true;state.meta.appVersion=APP_VERSION;document.title=`YKS Uzman Hoca V${APP_VERSION}`;

function cleanExactLegacySeedSnapshot(){
  const demoSessions=new Set(['1|18.08.2026|TYT Matematik|Üslü Sayılar|true','2|18.08.2026|TYT Matematik|Köklü Sayılar|false','3|17.08.2026|TYT Matematik|Problemler|true','4|17.08.2026|Fizik|Hareket|false','5|16.08.2026|TYT Matematik|Köklü Sayılar|false','6|16.08.2026|Türkçe|Paragraf|true','7|15.08.2026|TYT Matematik|Problemler|true','8|15.08.2026|TYT Matematik|Üslü Sayılar|true','9|14.08.2026|TYT Matematik|Köklü Sayılar|true','10|14.08.2026|Fizik|Hareket|true']);
  const demoTrials=new Set(['02.08.2026|TYT Deneme 1|51.5','09.08.2026|TYT Deneme 2|57','16.08.2026|TYT Deneme 3|61.25']);
  const sessions=state.sessions||[],trials=state.trials||[];
  const exactSessions=sessions.length===10&&sessions.every(x=>demoSessions.has(`${x?.id}|${x?.date}|${x?.subject}|${x?.topic}|${x?.correct}`));
  const exactTrials=trials.length===3&&trials.every(x=>demoTrials.has(`${x?.date}|${x?.name}|${Number(x?.net)}`));
  const noRealActivity=!(state.activityLog?.length||state.studyEvents?.length||state.miniTests?.history?.length||state.favorites?.length);
  if(exactSessions&&exactTrials&&noRealActivity){state.sessions=[];state.trials=[];state.topicMastery={};state.plan=[];state.todayCount=0;state.meta.legacyDemoSnapshotRemovedAt=Date.now();localStorage.setItem(KEY,JSON.stringify(state))}
}
cleanExactLegacySeedSnapshot();

let deferredInstallPrompt=null;
const CLOUD_DEVICE_KEY='yksUzmanHocaDeviceIdV5';
const cloudDeviceId=(()=>{let id=localStorage.getItem(CLOUD_DEVICE_KEY);if(!id){id=`dev-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,10)}`;localStorage.setItem(CLOUD_DEVICE_KEY,id)}return id})();
const CLOUD_RECONCILE_MIN_MS=15000;
let cloudEventSyncReady=false,cloudSchemaError='',cloudReconcilePromise=null,cloudReconcileTimer=null,cloudLastReconcileAt=0;

function applyStartupScreen(){const requested=new URLSearchParams(location.search).get('screen');if(requested&&document.getElementById(requested))setTimeout(()=>go(requested),0)}
function isStandalone(){return window.matchMedia('(display-mode: standalone)').matches||window.navigator.standalone===true}function isIOS(){return /iphone|ipad|ipod/i.test(navigator.userAgent)}
function showPwaToast(message,ms=4200){if(!window.pwaToast)return;pwaToast.textContent=message;pwaToast.classList.add('show');clearTimeout(showPwaToast.t);showPwaToast.t=setTimeout(()=>pwaToast.classList.remove('show'),ms)}
function updateInstallUI(){if(!window.installState||!window.installApp)return;if(isStandalone()){installState.textContent='Kurulu ✓';installState.className='install-state ready';installApp.style.display='none';return}if(deferredInstallPrompt){installState.textContent='Kurulmaya hazır';installState.className='install-state ready';installApp.style.display='inline-block';installApp.textContent='Ana Ekrana Kur'}else if(isIOS()){installState.textContent='Safari ile kurulabilir';installState.className='install-state ios';installApp.style.display='inline-block';installApp.textContent='iPhone/iPad Kurulum'}else{installState.textContent='Tarayıcı menüsünden kurulabilir';installState.className='install-state';installApp.style.display='none'}}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e;updateInstallUI()});window.addEventListener('appinstalled',()=>{deferredInstallPrompt=null;updateInstallUI();showPwaToast('YKS Uzman Hoca ana ekrana kuruldu. 🎓')});
async function installPwa(){if(deferredInstallPrompt){deferredInstallPrompt.prompt();const result=await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;updateInstallUI();if(result.outcome==='accepted')showPwaToast('Kurulum başlatıldı.');return}if(isIOS())showPwaToast('Safari’de Paylaş simgesine dokun → “Ana Ekrana Ekle” seçeneğini seç.',6500)}
function updateOnlineState(){const backOnline=navigator.onLine&&window.offlineBanner?.dataset.wasOffline==='1';if(window.offlineBanner){offlineBanner.classList.toggle('show',!navigator.onLine);if(!navigator.onLine)offlineBanner.dataset.wasOffline='1';else if(backOnline)offlineBanner.dataset.wasOffline='0'}if(backOnline){showPwaToast('İnternet bağlantısı geri geldi. Bulut senkronizasyonu yenileniyor.');maybeReconcileCloud('online',true)}}
async function initPwa(){updateInstallUI();updateOnlineState();window.addEventListener('online',updateOnlineState);window.addEventListener('offline',updateOnlineState);window.addEventListener('focus',()=>maybeReconcileCloud('focus'));document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')maybeReconcileCloud('resume')});if(window.installApp)installApp.onclick=installPwa;if('serviceWorker'in navigator&&location.protocol!=='file:'){try{const reg=await navigator.serviceWorker.register('/service-worker.js');reg.update().catch(()=>{})}catch(e){console.warn('Service Worker kaydı başarısız:',e)}}}
function setSyncStatus(text,type='warn'){if(!window.syncStatus)return;syncStatus.className='sync-status '+(type||'');syncStatus.innerHTML=`<span class="sync-dot"></span><span>${esc(text)}</span>`}function setSyncMessage(text){if(window.syncMessage)syncMessage.textContent=text}
function renderSyncUI(){if(!window.syncAuth)return;const signed=!!cloudUser;syncAuth.style.display=signed?'none':'grid';syncUser.classList.toggle('show',signed);syncNow.disabled=!signed||!cloudEventSyncReady;syncPull.disabled=!signed||!cloudEventSyncReady;if(signed)syncUserEmail.textContent=cloudUser.email||'Bağlı hesap';if(signed&&cloudEventSyncReady)setSyncStatus('V5 cihaz senkronizasyonu açık','online');else if(signed&&cloudSchemaError)setSyncStatus('Senkronizasyon kullanılamıyor','warn');else if(signed)setSyncStatus('Senkronizasyon hazırlanıyor…','warn');else if(cloudReady)setSyncStatus('Hesap girişi gerekli','warn')}

async function probeEventSyncSchema(){
  if(!sb||!cloudUser){cloudEventSyncReady=false;return false}
  const [eventProbe,stateProbe]=await Promise.all([sb.from('student_event_revisions').select('event_id').limit(1),sb.from('student_state').select('user_id').limit(1)]);
  const error=eventProbe.error||stateProbe.error;
  if(error){cloudEventSyncReady=false;cloudSchemaError=error.message||'Supabase V5 senkronizasyon şeması erişilemiyor.';setSyncStatus('Senkronizasyon kullanılamıyor','warn');setSyncMessage('Güvenli telefon/tablet senkronizasyonu doğrulanamadı: '+cloudSchemaError);return false}
  cloudSchemaError='';cloudEventSyncReady=true;return true;
}

async function initCloud(){if(location.protocol==='file:'){setSyncStatus('Demo modu','warn');setSyncMessage('Telefon/tablet senkronizasyonu için uygulamayı sunucudan aç.');renderSyncUI();return}try{const r=await fetch('/api/app-config'),cfg=await r.json();if(!cfg.supabaseUrl||!cfg.supabasePublishableKey){setSyncStatus('Supabase ayarı yok','warn');setSyncMessage('SUPABASE_URL ve SUPABASE_PUBLISHABLE_KEY tanımlandığında senkronizasyon açılır.');return}if(!window.supabase?.createClient)throw new Error('Supabase istemcisi yüklenemedi');sb=window.supabase.createClient(cfg.supabaseUrl,cfg.supabasePublishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});cloudReady=true;const {data:{session}}=await sb.auth.getSession();cloudUser=session?.user||null;if(cloudUser)await probeEventSyncSchema();renderSyncUI();if(cloudUser&&cloudEventSyncReady)await reconcileCloud({reason:'startup'});sb.auth.onAuthStateChange((event,session)=>{cloudUser=session?.user||null;if(!cloudUser){cloudEventSyncReady=false;cloudSchemaError='';renderSyncUI();return}renderSyncUI();if(event==='SIGNED_IN'||event==='TOKEN_REFRESHED'||event==='INITIAL_SESSION')setTimeout(async()=>{if(await probeEventSyncSchema()){renderSyncUI();await reconcileCloud({reason:'auth'})}else renderSyncUI()},0)})}catch(e){setSyncStatus('Bağlantı kurulamadı','warn');setSyncMessage('Bulut senkronizasyonu başlatılamadı: '+e.message)}}
function scheduleCloudSync(){if(!cloudReady||!cloudUser||!cloudEventSyncReady||!navigator.onLine)return;clearTimeout(cloudSyncTimer);cloudSyncTimer=setTimeout(()=>cloudPush(false),900)}
function maybeReconcileCloud(reason='resume',force=false){if(!navigator.onLine||!cloudReady||!cloudUser||!cloudEventSyncReady)return;const elapsed=Date.now()-cloudLastReconcileAt;if(!force&&elapsed<CLOUD_RECONCILE_MIN_MS)return;clearTimeout(cloudReconcileTimer);cloudReconcileTimer=setTimeout(()=>{void reconcileCloud({quiet:true,reason})},250)}
function cloudClone(x){try{return structuredClone(x)}catch{return JSON.parse(JSON.stringify(x||{}))}}
function cloudKey(x,kind){if(x?.id!==undefined&&x?.id!==null&&String(x.id)!=='')return String(x.id);if(x?.signature)return String(x.signature);if(kind==='trial')return [x?.type,x?.date,x?.name,x?.totalNet??x?.net].join('|');if(kind==='session')return [x?.createdAt,x?.date,x?.time,x?.subject,x?.topic,x?.source,x?.correct].join('|');if(kind==='activity')return [x?.createdAt,x?.dateKey,x?.subject,x?.topic,x?.source,x?.type,x?.count].join('|');return JSON.stringify(x||{})}
function mergeArrayByKey(local=[],remote=[],kind='',preferRemote=false){const map=new Map(),put=(x,fromRemote)=>{const k=cloudKey(x,kind);if(!k)return;const old=map.get(k);if(!old){map.set(k,cloudClone(x));return}const oldStamp=Number(old.updatedAt||old.createdAt||0),newStamp=Number(x?.updatedAt||x?.createdAt||0);if(newStamp>oldStamp||(newStamp===oldStamp&&fromRemote===preferRemote))map.set(k,cloudClone(x))};(local||[]).forEach(x=>put(x,false));(remote||[]).forEach(x=>put(x,true));return[...map.values()]}
function mergeStudyEvents(local=[],remote=[]){const out=mergeArrayByKey(local,remote,'studyEvent',true);return out.sort((a,b)=>Number(a.timestamp||0)-Number(b.timestamp||0))}
function mergeCloudStates(localState={},remoteState={},preferRemote=false){
  const local=cloudClone(localState),remote=cloudClone(remoteState),base=cloudClone(preferRemote?remote:local),other=preferRemote?local:remote;
  base.meta={...(other.meta||{}),...(base.meta||{})};base.meta.localUpdatedAt=Math.max(Number(local.meta?.localUpdatedAt||0),Number(remote.meta?.localUpdatedAt||0));base.meta.appVersion=APP_VERSION;
  base.studyEvents=mergeStudyEvents(local.studyEvents||[],remote.studyEvents||[]);
  base.sessions=mergeArrayByKey(local.sessions||[],remote.sessions||[],'session',preferRemote);
  base.activityLog=mergeArrayByKey(local.activityLog||[],remote.activityLog||[],'activity',preferRemote);
  base.trials=mergeArrayByKey(local.trials||[],remote.trials||[],'trial',preferRemote);
  base.favorites=mergeArrayByKey(local.favorites||[],remote.favorites||[],'favorite',preferRemote);
  base.fieldArchive={...(other.fieldArchive||{}),...(base.fieldArchive||{})};base.fieldArchive.sessions=mergeArrayByKey(local.fieldArchive?.sessions||[],remote.fieldArchive?.sessions||[],'session',preferRemote);base.fieldArchive.trials=mergeArrayByKey(local.fieldArchive?.trials||[],remote.fieldArchive?.trials||[],'trial',preferRemote);
  base.miniTests={...(other.miniTests||{}),...(base.miniTests||{})};base.miniTests.history=mergeArrayByKey(local.miniTests?.history||[],remote.miniTests?.history||[],'mini-history',preferRemote).sort((a,b)=>Number(b.id||0)-Number(a.id||0)).slice(0,40);
  base.costTracker={...(other.costTracker||{}),...(base.costTracker||{})};base.costTracker.records=mergeArrayByKey(local.costTracker?.records||[],remote.costTracker?.records||[],'cost',preferRemote).slice(-1500);
  base.counselorMessages=preferRemote?(remote.counselorMessages||local.counselorMessages||[]):(local.counselorMessages||remote.counselorMessages||[]);
  base.meta.dataArchitecture=base.studyEvents?.length?'StudyEvent-v5':(base.meta.dataArchitecture||other.meta?.dataArchitecture||'');return base;
}

function revisionIdFor(e){return `${Number(e?.updatedAt||e?.createdAt||0).toString(36)}-${cloudDeviceId}`}
async function pushEventLedger(){
  if(!cloudEventSyncReady||!cloudUser)return;
  window.YKSDataV5?.syncLegacy?.();
  const rows=(state.studyEvents||[]).filter(x=>x?.id).map(e=>({user_id:cloudUser.id,event_id:String(e.id),revision_id:revisionIdFor(e),event_updated_at:Number(e.updatedAt||e.createdAt||Date.now()),device_id:cloudDeviceId,event:cloudClone(e)}));
  for(let i=0;i<rows.length;i+=250){const {error}=await sb.from('student_event_revisions').upsert(rows.slice(i,i+250),{onConflict:'user_id,event_id,revision_id',ignoreDuplicates:true});if(error)throw error}
}
function chooseRevision(current,row){if(!current)return row;const a=Number(current.event_updated_at||0),b=Number(row.event_updated_at||0);if(b>a)return row;if(b<a)return current;return String(row.revision_id||'').localeCompare(String(current.revision_id||''))>0?row:current}
async function fetchEventLedger(){
  if(!cloudEventSyncReady||!cloudUser)return[];
  const {data,error}=await sb.from('student_event_revisions').select('event_id,revision_id,event_updated_at,device_id,event').eq('user_id',cloudUser.id).order('event_updated_at',{ascending:true}).limit(10000);if(error)throw error;
  const best=new Map();(data||[]).forEach(row=>best.set(row.event_id,chooseRevision(best.get(row.event_id),row)));return[...best.values()].map(x=>x.event).filter(Boolean)
}
async function syncEventLedger(){await pushEventLedger();const remoteEvents=await fetchEventLedger();state.studyEvents=mergeStudyEvents(state.studyEvents||[],remoteEvents);save(false);return state.studyEvents}

async function cloudPush(showMessage=true){if(!sb||!cloudUser||!cloudEventSyncReady)return false;if(!navigator.onLine){if(showMessage){setSyncStatus('Çevrimdışı','warn');setSyncMessage('Kayıt bu cihazda korundu. İnternet gelince otomatik senkronize edilecek.')}return false}try{if(showMessage)setSyncStatus('Kaydediliyor…','warn');await syncEventLedger();const payload=structuredClone(state);delete payload.studyEvents;payload.meta={...(payload.meta||{}),appVersion:APP_VERSION,eventLedger:'student_event_revisions'};const now=new Date().toISOString();const {error}=await sb.from('student_state').upsert({user_id:cloudUser.id,data:payload,updated_at:now},{onConflict:'user_id'});if(error)throw error;setSyncStatus('Senkronize','online');syncLastTime.textContent='Son kayıt: '+new Date().toLocaleString('tr-TR');if(showMessage)setSyncMessage('StudyEvent revizyonları korundu ve telefon/tablet verileri güvenli biçimde birleştirildi.');return true}catch(e){setSyncStatus('Senkron hatası','warn');setSyncMessage('Buluta kaydetme başarısız: '+e.message);return false}}
async function cloudFetch(){if(!sb||!cloudUser)return null;const {data,error}=await sb.from('student_state').select('data,updated_at').eq('user_id',cloudUser.id).limit(1);if(error)throw error;return data?.[0]||null}
async function applyCloudState(remote,{preferRemote=true}={}){if(!remote?.data)return false;cloudApplying=true;try{state=mergeCloudStates(state,remote.data,preferRemote);state.counselorMessages??=[];state.meta??={};state.meta.localUpdatedAt??=Date.now();state.meta.appVersion=APP_VERSION;await syncEventLedger();save(false);window.YKSDataV5?.syncLegacy?.();renderAll();syncLastTime.textContent='Birleştirildi: '+new Date(remote.updated_at).toLocaleString('tr-TR');return true}finally{cloudApplying=false}}
async function reconcileCloud({quiet=false,reason='manual'}={}){if(!sb||!cloudUser||!cloudEventSyncReady||!navigator.onLine)return false;if(cloudReconcilePromise)return cloudReconcilePromise;cloudReconcilePromise=(async()=>{try{if(!quiet)setSyncStatus('Kontrol ediliyor…','warn');const remote=await cloudFetch();if(!remote){await syncEventLedger();await cloudPush(!quiet);if(!quiet)setSyncMessage('İlk bulut kaydı oluşturuldu. StudyEvent revizyonları cihaz bazında korunuyor.');return true}const remoteStamp=Number(remote.data?.meta?.localUpdatedAt||0),localStamp=Number(state.meta?.localUpdatedAt||0),preferRemote=remoteStamp>localStamp;await applyCloudState(remote,{preferRemote});await cloudPush(false);setSyncStatus('Senkronize','online');if(!quiet)setSyncMessage('Telefon ve tablet StudyEvent kayıtları güvenli revizyon defteri üzerinden birleştirildi.');return true}catch(e){setSyncStatus('Senkron hatası','warn');if(!quiet)setSyncMessage('Senkronizasyon sırasında hata: '+e.message);else console.warn('Bulut reconcile başarısız ('+reason+'):',e);return false}})();try{return await cloudReconcilePromise}finally{cloudReconcilePromise=null;cloudLastReconcileAt=Date.now()}}
async function cloudLogin(){if(!sb||!cloudReady){setSyncMessage('Bulut bağlantısı henüz hazır değil.');return}const email=syncEmail.value.trim(),password=syncPassword.value;if(!email||!password){setSyncMessage('E-posta ve şifreyi gir.');return}setSyncStatus('Giriş yapılıyor…','warn');const {data,error}=await sb.auth.signInWithPassword({email,password});if(error){setSyncStatus('Giriş başarısız','warn');setSyncMessage(error.message);return}cloudUser=data.user;syncPassword.value='';renderSyncUI();if(!await probeEventSyncSchema()){renderSyncUI();return}renderSyncUI();await reconcileCloud({reason:'login'})}
async function cloudSignup(){if(!sb||!cloudReady){setSyncMessage('Bulut bağlantısı henüz hazır değil.');return}const email=syncEmail.value.trim(),password=syncPassword.value;if(!email||password.length<6){setSyncMessage('Geçerli e-posta ve en az 6 karakterlik şifre gir.');return}setSyncStatus('Hesap oluşturuluyor…','warn');const {data,error}=await sb.auth.signUp({email,password});if(error){setSyncStatus('Kayıt başarısız','warn');setSyncMessage(error.message);return}cloudUser=data.session?.user||null;syncPassword.value='';if(cloudUser){if(await probeEventSyncSchema()){renderSyncUI();await reconcileCloud({reason:'signup'});setSyncMessage('Hesap oluşturuldu ve güvenli V5 senkronizasyonu aktif.')}else renderSyncUI()}else{cloudEventSyncReady=false;renderSyncUI();setSyncStatus('E-posta doğrulaması','warn');setSyncMessage('Hesap oluşturuldu. E-posta doğrulaması açıksa gelen kutusundaki bağlantıyı onayladıktan sonra giriş yap.')}}
async function cloudLogout(){if(!sb)return;await sb.auth.signOut({scope:'local'});cloudUser=null;cloudEventSyncReady=false;cloudSchemaError='';renderSyncUI();setSyncMessage('Bu cihazdaki bulut oturumu kapatıldı. Yerel veriler silinmedi.')}
async function forceCloudPull(){if(!cloudUser||!cloudEventSyncReady)return;await reconcileCloud({quiet:false,reason:'manual-pull'})}
window.mergeYksCloudStates=mergeCloudStates;window.syncYksEventLedger=syncEventLedger;
if(window.syncLogin){syncLogin.onclick=cloudLogin;syncSignup.onclick=cloudSignup;syncLogout.onclick=cloudLogout;syncNow.onclick=()=>cloudPush(true);syncPull.onclick=forceCloudPull}
