let deferredInstallPrompt=null;
function applyStartupScreen(){const requested=new URLSearchParams(location.search).get('screen');if(requested&&document.getElementById(requested))setTimeout(()=>go(requested),0)}
function isStandalone(){return window.matchMedia('(display-mode: standalone)').matches||window.navigator.standalone===true}function isIOS(){return /iphone|ipad|ipod/i.test(navigator.userAgent)}
function showPwaToast(message,ms=4200){if(!window.pwaToast)return;pwaToast.textContent=message;pwaToast.classList.add('show');clearTimeout(showPwaToast.t);showPwaToast.t=setTimeout(()=>pwaToast.classList.remove('show'),ms)}
function updateInstallUI(){if(!window.installState||!window.installApp)return;if(isStandalone()){installState.textContent='Kurulu ✓';installState.className='install-state ready';installApp.style.display='none';return}if(deferredInstallPrompt){installState.textContent='Kurulmaya hazır';installState.className='install-state ready';installApp.style.display='inline-block';installApp.textContent='Ana Ekrana Kur'}else if(isIOS()){installState.textContent='Safari ile kurulabilir';installState.className='install-state ios';installApp.style.display='inline-block';installApp.textContent='iPhone/iPad Kurulum'}else{installState.textContent='Tarayıcı menüsünden kurulabilir';installState.className='install-state';installApp.style.display='none'}}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e;updateInstallUI()});window.addEventListener('appinstalled',()=>{deferredInstallPrompt=null;updateInstallUI();showPwaToast('YKS Uzman Hoca ana ekrana kuruldu. 🎓')});
async function installPwa(){if(deferredInstallPrompt){deferredInstallPrompt.prompt();const result=await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;updateInstallUI();if(result.outcome==='accepted')showPwaToast('Kurulum başlatıldı.');return}if(isIOS())showPwaToast('Safari’de Paylaş simgesine dokun → “Ana Ekrana Ekle” seçeneğini seç.',6500)}
function updateOnlineState(){if(!window.offlineBanner)return;offlineBanner.classList.toggle('show',!navigator.onLine);if(navigator.onLine&&offlineBanner.dataset.wasOffline==='1')showPwaToast('İnternet bağlantısı geri geldi. Bulut senkronizasyonu devam edebilir.');if(!navigator.onLine)offlineBanner.dataset.wasOffline='1'}
async function initPwa(){updateInstallUI();updateOnlineState();window.addEventListener('online',updateOnlineState);window.addEventListener('offline',updateOnlineState);if(window.installApp)installApp.onclick=installPwa;if('serviceWorker'in navigator&&location.protocol!=='file:'){try{const reg=await navigator.serviceWorker.register('/service-worker.js');reg.update().catch(()=>{})}catch(e){console.warn('Service Worker kaydı başarısız:',e)}}}
function setSyncStatus(text,type='warn'){if(!window.syncStatus)return;syncStatus.className='sync-status '+(type||'');syncStatus.innerHTML=`<span class="sync-dot"></span><span>${esc(text)}</span>`}function setSyncMessage(text){if(window.syncMessage)syncMessage.textContent=text}
function renderSyncUI(){if(!window.syncAuth)return;const signed=!!cloudUser;syncAuth.style.display=signed?'none':'grid';syncUser.classList.toggle('show',signed);syncNow.disabled=!signed;syncPull.disabled=!signed;if(signed){syncUserEmail.textContent=cloudUser.email||'Bağlı hesap';setSyncStatus('Senkronizasyon açık','online')}else if(cloudReady)setSyncStatus('Hesap girişi gerekli','warn')}
async function initCloud(){if(location.protocol==='file:'){setSyncStatus('Demo modu','warn');setSyncMessage('Telefon/tablet senkronizasyonu için uygulamayı sunucudan aç.');renderSyncUI();return}try{const r=await fetch('/api/app-config'),cfg=await r.json();if(!cfg.supabaseUrl||!cfg.supabasePublishableKey){setSyncStatus('Supabase ayarı yok','warn');setSyncMessage('SUPABASE_URL ve SUPABASE_PUBLISHABLE_KEY tanımlandığında senkronizasyon açılır.');return}if(!window.supabase?.createClient)throw new Error('Supabase istemcisi yüklenemedi');sb=window.supabase.createClient(cfg.supabaseUrl,cfg.supabasePublishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});cloudReady=true;const {data:{session}}=await sb.auth.getSession();cloudUser=session?.user||null;renderSyncUI();if(cloudUser)await reconcileCloud();sb.auth.onAuthStateChange((event,session)=>{cloudUser=session?.user||null;renderSyncUI();if(event==='SIGNED_IN'&&cloudUser)setTimeout(()=>reconcileCloud(),0)})}catch(e){setSyncStatus('Bağlantı kurulamadı','warn');setSyncMessage('Bulut senkronizasyonu başlatılamadı: '+e.message)}}
function scheduleCloudSync(){if(!cloudReady||!cloudUser)return;clearTimeout(cloudSyncTimer);cloudSyncTimer=setTimeout(()=>cloudPush(false),900)}
async function cloudPush(showMessage=true){if(!sb||!cloudUser)return false;try{if(showMessage)setSyncStatus('Kaydediliyor…','warn');const payload=structuredClone(state),now=new Date().toISOString();const {error}=await sb.from('student_state').upsert({user_id:cloudUser.id,data:payload,updated_at:now},{onConflict:'user_id'});if(error)throw error;setSyncStatus('Senkronize','online');syncLastTime.textContent='Son kayıt: '+new Date().toLocaleString('tr-TR');if(showMessage)setSyncMessage('Bu cihazdaki son değişiklikler buluta kaydedildi.');return true}catch(e){setSyncStatus('Senkron hatası','warn');setSyncMessage('Buluta kaydetme başarısız: '+e.message);return false}}
async function cloudFetch(){if(!sb||!cloudUser)return null;const {data,error}=await sb.from('student_state').select('data,updated_at').eq('user_id',cloudUser.id).limit(1);if(error)throw error;return data?.[0]||null}
async function applyCloudState(remote){if(!remote?.data)return false;cloudApplying=true;try{state=remote.data;state.counselorMessages??=[];state.meta??={};state.meta.localUpdatedAt??=Date.now();save(false);renderAll();syncLastTime.textContent='Buluttan alındı: '+new Date(remote.updated_at).toLocaleString('tr-TR');return true}finally{cloudApplying=false}}
async function reconcileCloud(){if(!sb||!cloudUser)return;try{setSyncStatus('Kontrol ediliyor…','warn');const remote=await cloudFetch();if(!remote){await cloudPush(true);setSyncMessage('İlk bulut kaydı oluşturuldu. Artık aynı hesapla tablette ve telefonda devam edebilirsin.');return}const remoteStamp=Number(remote.data?.meta?.localUpdatedAt||0),localStamp=Number(state.meta?.localUpdatedAt||0);if(remoteStamp>localStamp){await applyCloudState(remote);setSyncMessage('Buluttaki daha yeni çalışma verileri bu cihaza getirildi.')}else if(localStamp>remoteStamp){await cloudPush(false);setSyncMessage('Bu cihazdaki daha yeni çalışma verileri buluta aktarıldı.')}else{setSyncStatus('Senkronize','online');syncLastTime.textContent='Güncel: '+new Date(remote.updated_at).toLocaleString('tr-TR');setSyncMessage('Telefon ve tablet verileri aynı durumda.')}}catch(e){setSyncStatus('Senkron hatası','warn');setSyncMessage('Senkronizasyon sırasında hata: '+e.message)}}
async function cloudLogin(){if(!sb){setSyncMessage('Önce Supabase bağlantısı kurulmalı.');return}const email=syncEmail.value.trim(),password=syncPassword.value;if(!email||!password){setSyncMessage('E-posta ve şifreyi gir.');return}setSyncStatus('Giriş yapılıyor…','warn');const {data,error}=await sb.auth.signInWithPassword({email,password});if(error){setSyncStatus('Giriş başarısız','warn');setSyncMessage(error.message);return}cloudUser=data.user;syncPassword.value='';renderSyncUI();await reconcileCloud()}
async function cloudSignup(){if(!sb){setSyncMessage('Önce Supabase bağlantısı kurulmalı.');return}const email=syncEmail.value.trim(),password=syncPassword.value;if(!email||password.length<6){setSyncMessage('Geçerli e-posta ve en az 6 karakterlik şifre gir.');return}setSyncStatus('Hesap oluşturuluyor…','warn');const {data,error}=await sb.auth.signUp({email,password});if(error){setSyncStatus('Kayıt başarısız','warn');setSyncMessage(error.message);return}cloudUser=data.session?.user||null;syncPassword.value='';renderSyncUI();if(cloudUser){await reconcileCloud();setSyncMessage('Hesap oluşturuldu ve senkronizasyon aktif.')}else{setSyncStatus('E-posta doğrulaması','warn');setSyncMessage('Hesap oluşturuldu. E-posta doğrulaması açıksa gelen kutusundaki bağlantıyı onayladıktan sonra giriş yap.')}}
async function cloudLogout(){if(!sb)return;await sb.auth.signOut({scope:'local'});cloudUser=null;renderSyncUI();setSyncMessage('Bu cihazdaki bulut oturumu kapatıldı. Yerel veriler silinmedi.')}
async function forceCloudPull(){if(!cloudUser)return;try{const remote=await cloudFetch();if(!remote){setSyncMessage('Bulutta henüz kayıt yok.');return}await applyCloudState(remote);setSyncStatus('Buluttan yenilendi','online');setSyncMessage('Buluttaki çalışma verileri bu cihaza yüklendi.')}catch(e){setSyncMessage('Buluttan alma başarısız: '+e.message)}}
if(window.syncLogin){syncLogin.onclick=cloudLogin;syncSignup.onclick=cloudSignup;syncLogout.onclick=cloudLogout;syncNow.onclick=()=>cloudPush(true);syncPull.onclick=forceCloudPull}