(()=>{
  const VERSION=5;
  const norm=s=>String(s||'').toLocaleLowerCase('tr-TR').replace(/[^a-z0-9çğıöşü]+/g,' ').trim();
  const todayKey=()=>new Date().toLocaleDateString('sv-SE');
  const dateKey=v=>{const s=String(v||'').trim();if(/^\d{4}-\d{2}-\d{2}$/.test(s))return s;const m=s.match(/^(\d{1,2})\.(\d{1,2})\.(\d{4})$/);return m?`${m[3]}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`:''};
  const parseDate=v=>{const k=dateKey(v);return k?new Date(k+'T12:00:00'):null};
  const timestampOf=(x={})=>{if(Number(x.createdAt))return Number(x.createdAt);if(x.timestamp){const n=Date.parse(x.timestamp);if(Number.isFinite(n))return n}const k=x.dateKey||dateKey(x.date);if(!k)return Date.now();const tm=String(x.time||'12:00').match(/(\d{1,2}):(\d{2})/),hh=tm?tm[1].padStart(2,'0'):'12',mm=tm?tm[2]:'00',n=Date.parse(`${k}T${hh}:${mm}:00`);return Number.isFinite(n)?n:Date.now()};
  const hash=s=>{let h=2166136261;for(const ch of String(s||'')){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)}return(h>>>0).toString(36)};
  const uid=prefix=>`${prefix}:${Date.now().toString(36)}:${Math.random().toString(36).slice(2,9)}`;
  const clone=x=>{try{return structuredClone(x)}catch{return JSON.parse(JSON.stringify(x))}};
  const examSubject=(raw='',explicit='')=>{const s=String(raw||'').trim(),m=s.match(/^\s*(TYT|AYT)\b\s*/i),exam=String(explicit||m?.[1]||'TYT').toUpperCase()==='AYT'?'AYT':'TYT',subject=s.replace(/^\s*(TYT|AYT)\b\s*/i,'').trim()||'Genel';return{exam,subject}};
  const normalizeResult=v=>v===true||v==='correct'?'correct':v===false||v==='wrong'?'wrong':'unknown';
  const sourceLabel=s=>String(s||'study').trim()||'study';
  const sourceFamily=s=>{const x=sourceLabel(s);if(['photo-question','text-question','question-solve','solve'].includes(x))return'solve';if(x==='mini-test')return'mini-test';if(x==='teacher-check'||x==='teacher')return'teacher';if(x==='trial')return'trial';return x};
  const topicKeyOf=raw=>{const key=String(raw.topicKey||raw.meta?.topicId||'').trim();return/^(tyt|ayt)\.[a-z0-9-]+\.[a-z0-9-]+$/i.test(key)?key.toLowerCase():norm(key||raw.topic||'')};
  const topicIdentity=event=>event.meta?.topicId||window.YKSTopicTaxonomyV1?.find?.({exam:event.exam,subject:event.subject,topic:event.topic})?.id||event.topicKey||norm(event.topic);
  const activeEvent=x=>!(x?.source==='topic-test'&&x?.meta?.deletedAt);
  const count=v=>Number.isInteger(Number(v))?Number(v):0;
  function measurementOf(event={}){
    if(event.source==='topic-test'&&event.meta?.schema==='topic-test-v1'){
      const counts=event.meta?.counts||{},correct=count(counts.correct),wrong=count(counts.wrong),blank=count(counts.blank),questionCount=count(event.questionCount),answeredCount=correct+wrong,evaluatedCount=correct+wrong+blank;
      return{questionCount,evaluatedCount,answeredCount,correct,wrong,blank,net:correct-wrong/4,accuracy:questionCount?correct/questionCount:null};
    }
    const questionCount=Math.max(0,Number(event.questionCount||0)),measured=event.result==='correct'||event.result==='wrong',evaluatedCount=measured?Math.max(1,questionCount||1):0,correct=event.result==='correct'?evaluatedCount:0,wrong=event.result==='wrong'?evaluatedCount:0,blank=0;
    return{questionCount,evaluatedCount,answeredCount:evaluatedCount,correct,wrong,blank,net:correct-wrong/4,accuracy:evaluatedCount?correct/evaluatedCount:null};
  }
  const publishers=[
    {key:'345',title:'345',aliases:['345','üç dört beş','uc dort bes']},
    {key:'bilgi-sarmal',title:'Bilgi Sarmal',aliases:['bilgi sarmal']},
    {key:'orijinal',title:'Orijinal',aliases:['orijinal']},
    {key:'3d',title:'3D',aliases:['3d']},
    {key:'apotemi',title:'Apotemi',aliases:['apotemi']}
  ];
  function normalizeResource(value){const title=String(value||'').trim(),key=norm(title),known=publishers.find(x=>x.aliases.some(a=>norm(a)===key));return{title,key:known?.key||`custom:${key.replace(/\s+/g,'-')}`,publisher:known?.title||'Diğer'}}
  function validateTopicTest(raw={}){
    const errors=[],exam=String(raw.exam||'').toUpperCase(),taxonomy=window.YKSTopicTaxonomyV1,topic=taxonomy?.get?.(raw.topicId),total=Number(raw.total??raw.questionCount),correct=Number(raw.correct),wrong=Number(raw.wrong),blank=Number(raw.blank),duration=raw.durationMinutes===undefined||raw.durationMinutes===null||raw.durationMinutes===''?null:Number(raw.durationMinutes),resource=String(raw.resource||'').trim(),testName=String(raw.testName||'').trim(),date=dateKey(raw.dateKey||raw.date||todayKey());
    if(!['TYT','AYT'].includes(exam))errors.push('exam');
    if(!topic||!topic.active||topic.exam!==exam||topic.subjectId!==String(raw.subjectId||topic?.subjectId||''))errors.push('topicId');
    if(!resource||resource.length>120)errors.push('resource');
    if(!Number.isInteger(total)||total<1||total>500)errors.push('total');
    for(const [key,value] of Object.entries({correct,wrong,blank}))if(!Number.isInteger(value)||value<0)errors.push(key);
    if(Number.isInteger(total)&&Number.isInteger(correct)&&Number.isInteger(wrong)&&Number.isInteger(blank)&&correct+wrong+blank!==total)errors.push('counts');
    if(duration!==null&&(!Number.isInteger(duration)||duration<1||duration>1440))errors.push('durationMinutes');
    const parsed=date?new Date(`${date}T12:00:00`):null;if(!date||!parsed||Number.isNaN(parsed.getTime())||parsed.toLocaleDateString('sv-SE')!==date||date>todayKey())errors.push('dateKey');
    if(testName.length>120)errors.push('testName');
    if(!String(raw.actionId||'').trim())errors.push('actionId');
    return{valid:errors.length===0,errors,value:{exam,topic,total,correct,wrong,blank,durationMinutes:duration,resource:normalizeResource(resource),testName,dateKey:date,actionId:String(raw.actionId||'').trim()}};
  }

  function ensure(){state.meta??={};state.studyEvents??=[];state.dataV5??={schemaVersion:VERSION,createdAt:Date.now(),activeSolveEventId:''};state.dataV5.schemaVersion=VERSION;state.dataV5.activeSolveEventId??=''}
  function cleanKnownDemoData(){
    state.meta??={};if(state.meta.v5DemoCleaned)return;
    const demoSessions=new Set(['1|18.08.2026|TYT Matematik|Üslü Sayılar|true','2|18.08.2026|TYT Matematik|Köklü Sayılar|false','3|17.08.2026|TYT Matematik|Problemler|true','4|17.08.2026|Fizik|Hareket|false','5|16.08.2026|TYT Matematik|Köklü Sayılar|false','6|16.08.2026|Türkçe|Paragraf|true','7|15.08.2026|TYT Matematik|Problemler|true','8|15.08.2026|TYT Matematik|Üslü Sayılar|true','9|14.08.2026|TYT Matematik|Köklü Sayılar|true','10|14.08.2026|Fizik|Hareket|true']);
    state.sessions=(state.sessions||[]).filter(x=>x?.source||!demoSessions.has(`${x?.id}|${x?.date}|${x?.subject}|${x?.topic}|${x?.correct}`));
    const demoTrials=new Set(['02.08.2026|TYT Deneme 1|51.5','09.08.2026|TYT Deneme 2|57','16.08.2026|TYT Deneme 3|61.25']);state.trials=(state.trials||[]).filter(x=>x?.subjects||!demoTrials.has(`${x?.date}|${x?.name}|${Number(x?.net)}`));state.meta.v5DemoCleaned=true;
  }
  function fieldAllowed(event,track=state.profile?.track||''){
    if(event?.source==='trial'){
      const type=String(event.meta?.trial?.type||event.subject||'TYT').toUpperCase();if(type==='TYT'||!track)return true;return type===`AYT-${track}`;
    }
    if(!track||event.exam!=='AYT')return true;const s=norm(event.subject);
    if(track==='SAY')return /matematik|geometri|fizik|kimya|biyoloji/.test(s);
    if(track==='EA')return /matematik|geometri|edebiyat|tarih|coğraf/.test(s);
    return true;
  }
  function normalizeEvent(raw={}){
    const {exam,subject}=examSubject(raw.subject,raw.exam),ts=Number(raw.timestamp||Date.now());return{id:String(raw.id||uid('event')),timestamp:Number.isFinite(ts)?ts:Date.now(),dateKey:String(raw.dateKey||new Date(Number.isFinite(ts)?ts:Date.now()).toLocaleDateString('sv-SE')),source:sourceLabel(raw.source),exam,track:String(raw.track||state.profile?.track||''),subject,subjectKey:norm(raw.subjectKey||subject),topic:String(raw.topic||'').trim(),topicKey:topicKeyOf(raw),curriculumOutcome:String(raw.curriculumOutcome||raw.curriculum_outcome||'').trim(),result:normalizeResult(raw.result),difficulty:String(raw.difficulty||'').trim(),interaction:String(raw.interaction||'studied').trim(),questionCount:sourceLabel(raw.source)==='trial'?0:Math.max(0,Number(raw.questionCount??raw.count??1)||0),signals:Array.isArray(raw.signals)?[...new Set(raw.signals.map(String))]:[],meta:raw.meta&&typeof raw.meta==='object'?clone(raw.meta):{},createdAt:Number(raw.createdAt||ts||Date.now()),updatedAt:Number(raw.updatedAt||Date.now())};
  }
  function upsert(raw){ensure();const next=normalizeEvent(raw),i=state.studyEvents.findIndex(x=>x?.id===next.id);if(i<0){state.studyEvents.push(next);return next}const current=state.studyEvents[i];state.studyEvents[i]=normalizeEvent({...current,...next,meta:{...(current.meta||{}),...(next.meta||{})},signals:[...(current.signals||[]),...(next.signals||[])],createdAt:current.createdAt||next.createdAt,updatedAt:Date.now()});return state.studyEvents[i]}
  function deterministic(kind,x,index){if(x?.id!==undefined&&x?.id!==null&&String(x.id)!=='')return`legacy-${kind}:${String(x.id)}`;return`legacy-${kind}:${hash([x?.dateKey,x?.date,x?.time,x?.createdAt,x?.subject,x?.topic,x?.source,x?.correct,x?.name,x?.type,x?.net,x?.totalNet,index].join('|'))}`}
  function ingestSession(x,index,archived=false){if(!x)return;const id=deterministic('session',x,index),{exam,subject}=examSubject(x.subject),existed=state.studyEvents?.some(e=>e?.id===id),precise=!!(x.time||Number(x.createdAt));upsert({id,timestamp:timestampOf(x),dateKey:dateKey(x.date)||todayKey(),source:x.source||'measurement',exam,subject,topic:x.topic||'',curriculumOutcome:x.curriculum_outcome||'',result:typeof x.correct==='boolean'?x.correct:'unknown',difficulty:x.difficulty||'',interaction:'answered',questionCount:1,meta:{legacyKind:'session',legacyId:x.id??null,archived,preciseTime:precise||existed}})}
  function ingestActivity(x,index){if(!x)return;const id=deterministic('activity',x,index),{exam,subject}=examSubject(x.subject);upsert({id,timestamp:timestampOf(x),dateKey:x.dateKey||dateKey(x.date)||todayKey(),source:x.source||x.type||'activity',exam,subject,topic:x.topic||'',result:'unknown',interaction:'studied',questionCount:Number(x.count||1),meta:{legacyKind:'activity',legacyId:x.id??null}})}
  function ingestTrial(x,index,archived=false){if(!x)return;const id=deterministic('trial',x,index),type=String(x.type||'TYT').toUpperCase(),exam=type.startsWith('AYT')?'AYT':'TYT';upsert({id,timestamp:timestampOf(x),dateKey:dateKey(x.date)||todayKey(),source:'trial',exam,subject:type,topic:'',result:'unknown',interaction:'exam',questionCount:0,meta:{legacyKind:'trial',legacyId:x.id??null,archived,trial:clone(x)}})}
  function syncLegacy(){ensure();cleanKnownDemoData();(state.sessions||[]).forEach((x,i)=>ingestSession(x,i,false));(state.activityLog||[]).forEach((x,i)=>ingestActivity(x,i));(state.trials||[]).forEach((x,i)=>ingestTrial(x,i,false));(state.fieldArchive?.sessions||[]).forEach((x,i)=>ingestSession(x,100000+i,true));(state.fieldArchive?.trials||[]).forEach((x,i)=>ingestTrial(x,100000+i,true));state.meta.v5Migrated=true;state.meta.v5LastSyncAt=Date.now();return state.studyEvents}

  let baseSave=null;
  function installSaveBridge(){if(window.__yksV5SaveBridge)return;if(typeof save!=='function'){setTimeout(installSaveBridge,60);return}baseSave=save;const wrapped=function(touch=true){try{syncLegacy()}catch(e){console.warn('V5 legacy sync',e)}return baseSave(touch)};save=wrapped;window.save=wrapped;window.__yksV5SaveBridge=true}
  function persist(touch=true){if(typeof save==='function')return save(touch);try{localStorage.setItem('yksUzmanHocaV4',JSON.stringify(state))}catch{}}
  function record(raw,{persistNow=true}={}){syncLegacy();const e=upsert({...raw,id:raw.id||uid(sourceFamily(raw.source||'study'))});if(persistNow)persist();return e}
  function recordTopicTest(raw={},options={}){const checked=validateTopicTest(raw);if(!checked.valid)return{ok:false,errors:checked.errors};const x=checked.value,id=`topic-test:${x.actionId}`,existing=state.studyEvents?.find(e=>e?.id===id);if(existing)return{ok:true,event:existing,duplicate:true};const event=record({id,source:'topic-test',interaction:'completed-external-test',result:'unknown',exam:x.exam,subject:x.topic.subject,subjectKey:x.topic.subjectId,topic:x.topic.topic,topicKey:x.topic.id,questionCount:x.total,signals:['aggregate-performance'],dateKey:x.dateKey,timestamp:new Date(`${x.dateKey}T12:00:00`).getTime(),meta:{schema:'topic-test-v1',inputType:'manual-aggregate',topicId:x.topic.id,counts:{correct:x.correct,wrong:x.wrong,blank:x.blank},durationMinutes:x.durationMinutes,resource:x.resource.title,resourceKey:x.resource.key,resourcePublisher:x.resource.publisher,testName:x.testName,actionId:x.actionId,deletedAt:null,deletedReason:''}},options);return{ok:true,event,duplicate:false}}
  function patch(id,changes={},options={}){syncLegacy();const cur=state.studyEvents.find(x=>x.id===id);if(!cur)return null;const signals=options.replaceSignals?(changes.signals||[]):[...(cur.signals||[]),...(changes.signals||[])],e=upsert({...cur,...changes,id,meta:{...(cur.meta||{}),...(changes.meta||{})},signals});persist();return e}
  function events({relevant=true,includeTrials=true,includeDeleted=false}={}){syncLegacy();let rows=state.studyEvents.filter(Boolean);if(!includeDeleted)rows=rows.filter(activeEvent);if(relevant)rows=rows.filter(x=>fieldAllowed(x));if(!includeTrials)rows=rows.filter(x=>x.source!=='trial');return rows.slice().sort((a,b)=>a.timestamp-b.timestamp)}

  function topicMetrics(rows){
    const groups=new Map();rows.filter(x=>topicIdentity(x)&&x.source!=='trial').forEach(x=>{const identity=topicIdentity(x),subjectKey=x.subjectKey||norm(x.subject),k=`${x.exam}|${subjectKey}|${identity}`;if(!groups.has(k))groups.set(k,{exam:x.exam,subject:x.subject,subjectKey,topic:x.topic,topicKey:identity,events:[]});groups.get(k).events.push(x)});
    return[...groups.values()].map(g=>{const all=g.events.slice().sort((a,b)=>a.timestamp-b.timestamp),measured=all.filter(x=>measurementOf(x).evaluatedCount>0).slice(-12),recentMeasured=measured.slice(-5),total=measured.reduce((a,x)=>a+measurementOf(x).questionCount,0),correct=measured.reduce((a,x)=>a+measurementOf(x).correct,0),wrong=measured.reduce((a,x)=>a+measurementOf(x).wrong,0),blank=measured.reduce((a,x)=>a+measurementOf(x).blank,0),net=correct-wrong/4,score=total?Math.round(correct/total*100):null,recentWrong=recentMeasured.reduce((a,x)=>a+measurementOf(x).wrong,0),cutoff=Date.now()-7*86400000,recentSignals=all.filter(x=>x.timestamp>=cutoff).reduce((a,x)=>a+(x.signals||[]).filter(s=>['wrong','unable','stuck'].includes(s)).length,0),last=all.at(-1),lastDate=last?.dateKey||'',d=parseDate(lastDate),staleDays=d?Math.max(0,Math.floor((Date.now()-d.getTime())/86400000)):999,todayCount=all.filter(x=>x.dateKey===todayKey()).reduce((a,x)=>a+measurementOf(x).questionCount,0),confidence=total>=5?'Güçlü':total>=3?'Orta':total>=1?'Az':'Ölçüm yok';return{...g,total,correct,wrong,blank,net,score,recentWrong,recentSignals,lastDate,staleDays,todayCount,confidence,lastTimestamp:last?.timestamp||0,events:all}}).sort((a,b)=>{const av=a.score===null?55:a.score,bv=b.score===null?55:b.score;return av-bv||b.recentSignals-a.recentSignals||b.total-a.total||a.topic.localeCompare(b.topic,'tr')});
  }
  function learningModel(){const rows=events({relevant:true,includeTrials:true}),study=rows.filter(x=>x.source!=='trial'),measures=study.map(measurementOf),questionCount=measures.reduce((a,x)=>a+x.questionCount,0),measuredCount=measures.reduce((a,x)=>a+x.evaluatedCount,0),correct=measures.reduce((a,x)=>a+x.correct,0),wrong=measures.reduce((a,x)=>a+x.wrong,0),blank=measures.reduce((a,x)=>a+x.blank,0),activeDays=new Set(study.filter(x=>measurementOf(x).questionCount>0).map(x=>x.dateKey).filter(Boolean)),sourceCounts={solve:0,miniTest:0,teacher:0,other:0,trials:rows.filter(x=>x.source==='trial').length};study.forEach(x=>{const n=measurementOf(x).questionCount,f=sourceFamily(x.source);if(f==='solve')sourceCounts.solve+=n;else if(f==='mini-test')sourceCounts.miniTest+=n;else if(f==='teacher')sourceCounts.teacher+=n;else sourceCounts.other+=n});const topics=topicMetrics(study);return{events:rows,studyEvents:study,topics,metrics:topics,questionCount,measuredCount,correct,wrong,blank,net:correct-wrong/4,accuracy:measuredCount?Math.round(correct/measuredCount*100):null,activeDays,sourceCounts,track:state.profile?.track||'',todayCount:study.filter(x=>x.dateKey===todayKey()).reduce((a,x)=>a+measurementOf(x).questionCount,0)}}
  function trials(){return events({relevant:true,includeTrials:true}).filter(x=>x.source==='trial').map(x=>clone(x.meta?.trial||{})).filter(x=>Object.keys(x).length)}
  function recentForTopic(topic,limit=5){const raw=String(topic||''),key=/^(tyt|ayt)\./i.test(raw)?raw.toLowerCase():norm(raw);return events({relevant:true,includeTrials:false}).filter(x=>(topicIdentity(x)===key||x.topicKey===key)&&measurementOf(x).evaluatedCount>0).slice(-limit).reverse()}
  function setSolveFeedback(kind){const id=state.dataV5?.activeSolveEventId;if(!id)return null;const cur=state.studyEvents.find(x=>x.id===id);if(!cur)return null;const map={unable:{result:'unknown',interaction:'unable',signal:'unable'},wrong:{result:'wrong',interaction:'wrong',signal:'wrong'},checked:{result:'unknown',interaction:'checked',signal:'checked'}},cfg=map[kind];if(!cfg)return null;const keep=(cur.signals||[]).filter(s=>!['unable','wrong','checked'].includes(s));return patch(id,{result:cfg.result,interaction:cfg.interaction,signals:[...keep,cfg.signal],meta:{selfReport:kind}},{replaceSignals:true})}
  function markStuck(){const id=state.dataV5?.activeSolveEventId;if(!id)return null;const cur=state.studyEvents.find(x=>x.id===id);if(!cur)return null;return patch(id,{signals:[...(cur.signals||[]),'stuck'],meta:{stuck:true}},{replaceSignals:true})}

  function installSolveBridge(){
    if(window.__yksV5SolveBridge)return;if(typeof liveSolve!=='function'){setTimeout(installSolveBridge,120);return}const base=liveSolve;
    const wrapped=async args=>{const ok=await base(args);if(!ok)return ok;const x=lastLiveResult||{},hasImage=!!args?.image,hasText=!!String(args?.text||'').trim(),inputType=hasImage&&hasText?'image+text':hasImage?'image':'text',mode=hasImage?'photo-question':hasText?'text-question':'question-solve',questionSig=hash(`${String(args?.text||'')}|${String(args?.image||'').slice(0,500)}`),e=record({source:mode,exam:x.exam||'TYT',subject:x.subject||'Genel',topic:x.topic||'',curriculumOutcome:x.curriculum_outcome||'',difficulty:x.difficulty||'',result:'unknown',interaction:'solved',questionCount:1,signals:[],meta:{questionHash:questionSig,inputType}},{persistNow:false});state.dataV5.activeSolveEventId=e.id;persist();setTimeout(renderFeedback,0);return ok};liveSolve=wrapped;window.liveSolve=wrapped;window.__yksV5SolveBridge=true;
  }
  function renderFeedback(){
    const root=document.getElementById('solution');if(!root)return;let box=root.querySelector('.v5-solve-feedback');const event=state.studyEvents.find(x=>x.id===state.dataV5?.activeSolveEventId);if(!event)return;if(!box){box=document.createElement('div');box.className='card v5-solve-feedback';const row=root.querySelector('.action-row');if(row)row.insertAdjacentElement('afterend',box);else root.appendChild(box)}const selected=event.meta?.selfReport||'';
    box.innerHTML=`<div class="v5-feedback-head"><div><b>Bu soru sende nasıldı?</b><small>Bu seçim Koç ve Kişisel Öğretmenin sonraki önerisini akıllılaştırır.</small></div><span class="pill">V5 öğrenme sinyali</span></div><div class="v5-feedback-actions"><button data-v5-feedback="unable" class="${selected==='unable'?'active':''}">😕 Yapamadım</button><button data-v5-feedback="wrong" class="${selected==='wrong'?'active':''}">❌ Yanlış yaptım</button><button data-v5-feedback="checked" class="${selected==='checked'?'active':''}">✅ Sadece kontrol ettim</button></div><div class="v5-feedback-note">${selected==='wrong'?'Yanlış olarak ölçüme katıldı.':selected==='unable'?'Başarı yüzdesine eklenmedi; güçlü eksik-konu sinyali olarak kaydedildi.':selected==='checked'?'Yalnız çalışma aktivitesi olarak sayıldı.':'Seçim yapmazsan yalnız çalışma aktivitesi olarak kalır.'}</div>`;
    box.querySelectorAll('[data-v5-feedback]').forEach(b=>b.onclick=()=>{setSolveFeedback(b.dataset.v5Feedback);renderFeedback();try{window.renderHome?.()}catch{};try{window.renderStats?.()}catch{}});
  }
  const style=document.createElement('style');style.textContent=`.v5-solve-feedback{margin-top:14px}.v5-feedback-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.v5-feedback-head small{display:block;color:var(--muted);margin-top:4px;line-height:1.4}.v5-feedback-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.v5-feedback-actions button{border:1px solid var(--line);background:var(--surface);border-radius:12px;padding:9px 12px;color:var(--ink);font-weight:750}.v5-feedback-actions button.active{border-color:#8e7df4;background:#f2efff;color:#4f39bd}.v5-feedback-note{font-size:11px;color:var(--muted);margin-top:9px}@media(max-width:620px){.v5-feedback-head{flex-direction:column}.v5-feedback-actions{display:grid;grid-template-columns:1fr}}`;document.head.appendChild(style);
  document.addEventListener('click',e=>{if(e.target.closest('#solution [data-go="stuck"]')||e.target.closest('#stuck [data-stuck-mode]'))markStuck()},true);

  ensure();cleanKnownDemoData();syncLegacy();installSaveBridge();installSolveBridge();window.YKSDataV5={version:VERSION,syncLegacy,record,recordTopicTest,validateTopicTest,measurementOf,normalizeResource,patch,getEvents:events,getLearningModel:learningModel,getTrials:trials,recentForTopic,setSolveFeedback,markStuck,fieldAllowed,norm,dateKey,todayKey};state.meta.dataArchitecture='StudyEvent-v5';persist(false);
})();
