import assert from 'node:assert/strict';
import fs from 'node:fs';
import test from 'node:test';
import vm from 'node:vm';

const code=fs.readFileSync(new URL('../app-teacher-pilot-v1.js',import.meta.url),'utf8');
const checkpoints=[1,3,7,14,30];
function engine(){const state={studyEvents:[]},context={state,console,Date,structuredClone};context.window=context;context.globalThis=context;context.YKSDataV5={record(e){state.studyEvents.push(structuredClone(e));return e}};vm.createContext(context);vm.runInContext(code,context);return context.YKSTeacherPilotV1}
function dateKey(day){const d=new Date('2026-08-24T12:00:00Z');d.setUTCDate(d.getUTCDate()+day);return d.toISOString().slice(0,10)}
function simulate(profile){const P=engine();let memory=null,previousIntervalDays=0;const trail=[];for(const day of checkpoints){if(profile.reopenAt?.includes(day)&&memory)memory.closureComplete=false;const today=dateKey(day),mode=memory?P.resumeMode({previousMode:memory.previousMode,nextMode:memory.nextMode,nextReviewDate:memory.nextReview.dateKey,today,closureComplete:memory.closureComplete}):P.decideTeacherSession(profile.start).mode,response=profile.responses?.[day];let nextMode='',review=null;if(response){const answered=Number(response.answered??P.modeConfig[mode].count),correct=Number(response.correct||0),wrong=Number(response.wrong||0),unable=Number(response.unable||0),score=answered?Math.round(correct/answered*100):0,raw=P.decideTeacherSession({total:answered,score,recentWrong:wrong,recentSignals:unable,staleDays:0});nextMode=P.transitionMode(mode,raw.mode);review=P.nextReview({dateKey:today,answered,correct,staleCheck:mode==='spaced'||mode==='maintain',previousIntervalDays});previousIntervalDays=review.days;memory={previousMode:mode,nextMode,nextReview:review,closureComplete:response.closureComplete??wrong+unable===0};trail.push({day,mode,answered,correct,wrong,unable,nextMode,reviewDays:review.days})}else trail.push({day,mode,answered:0,nextMode:'',reviewDays:0})}return{P,trail,memory,nextModeAt(day){return P.resumeMode({previousMode:memory.previousMode,nextMode:memory.nextMode,nextReviewDate:memory.nextReview.dateKey,today:dateKey(day),closureComplete:memory.closureComplete})}}}
const modes=x=>x.trail.map(r=>r.mode);

test('longitudinal 01 — no-data student is measured before progression',()=>{const x=simulate({start:{total:0,score:null},responses:{1:{answered:5,correct:3,wrong:2,closureComplete:true},3:{answered:5,correct:4,wrong:1,closureComplete:true},7:{answered:5,correct:4,wrong:1,closureComplete:true},14:{answered:3,correct:3},30:{answered:3,correct:3}}});assert.deepEqual(modes(x),['diagnostic','repair','reinforce','spaced','spaced']);assert.equal(x.trail[0].answered,5)});

test('longitudinal 02 — continuously wrong student never reaches challenge',()=>{const bad={answered:5,correct:1,wrong:4,closureComplete:false},x=simulate({start:{total:0,score:null},responses:Object.fromEntries(checkpoints.map(d=>[d,bad]))});assert.deepEqual(modes(x),['diagnostic','repair','repair','repair','repair']);assert.ok(!modes(x).includes('challenge'))});

test('longitudinal 03 — repeated error reopens repair after apparent recovery',()=>{const x=simulate({start:{total:0,score:null},reopenAt:[14],responses:{1:{answered:5,correct:3,wrong:2,closureComplete:true},3:{answered:5,correct:5},7:{answered:5,correct:5},14:{answered:5,correct:4,wrong:1,closureComplete:true},30:{answered:5,correct:4,wrong:1,closureComplete:true}}});assert.deepEqual(modes(x),['diagnostic','repair','reinforce','repair','reinforce'])});

test('longitudinal 04 — medium student stays in controlled reinforcement',()=>{const mid={answered:5,correct:3,wrong:1,unable:1,closureComplete:true},x=simulate({start:{total:5,score:65},responses:Object.fromEntries(checkpoints.map(d=>[d,mid]))});assert.deepEqual(modes(x),['reinforce','reinforce','reinforce','reinforce','reinforce'])});

test('longitudinal 05 — successful student receives short maintenance, not repeated long work',()=>{const x=simulate({start:{total:8,score:95,staleDays:1},responses:{1:{answered:5,correct:5},3:{answered:3,correct:3},7:{answered:3,correct:3},14:{answered:3,correct:3},30:{answered:3,correct:3}}});assert.deepEqual(modes(x),['challenge','maintain','maintain','maintain','maintain']);assert.deepEqual(x.trail.slice(1).map(r=>r.answered),[3,3,3,3])});

test('longitudinal 06 — forgetting student is checked with spaced review then repaired',()=>{const x=simulate({start:{total:8,score:95,staleDays:1},responses:{1:{answered:5,correct:5},30:{answered:3,correct:1,wrong:2,closureComplete:false}}});assert.deepEqual(modes(x),['challenge','maintain','maintain','maintain','spaced']);assert.equal(x.trail.at(-1).nextMode,'repair');assert.equal(x.nextModeAt(31),'repair')});

test('longitudinal 07 — high effort without progress does not create fake mastery',()=>{const weak={answered:5,correct:2,wrong:3,closureComplete:false},x=simulate({start:{total:5,score:40},responses:Object.fromEntries(checkpoints.map(d=>[d,weak]))});assert.deepEqual(modes(x),['repair','repair','repair','repair','repair']);assert.ok(x.trail.every(r=>r.nextMode==='repair'))});

test('longitudinal 08 — easy-question farming cannot satisfy challenge or earn teacher points',()=>{const P=engine(),easy=Array.from({length:30},(_,i)=>({id:`easy-${i}`,difficulty:'KOLAY'}));let points=0;for(const day of checkpoints){const selection=P.difficultySelection(easy,P.modeConfig.challenge);assert.equal(selection.items.length,0,`day ${day}`);if(selection.distributionExact)points+=P.rewardFor({attempt:true,correct:true}).points}assert.equal(points,0)});

test('longitudinal 09 — student returning after a break keeps unresolved repair debt',()=>{const x=simulate({start:{total:5,score:40},responses:{1:{answered:5,correct:2,wrong:3,closureComplete:false},30:{answered:5,correct:3,wrong:2,closureComplete:false}}});assert.deepEqual(modes(x),['repair','repair','repair','repair','repair'])});

test('longitudinal 10 — short-task student reaches a 30-day interval with three-question checks',()=>{const short={answered:3,correct:3},x=simulate({start:{total:8,score:85,staleDays:1},responses:Object.fromEntries(checkpoints.map(d=>[d,short]))});assert.deepEqual(modes(x),['maintain','maintain','maintain','maintain','maintain']);assert.deepEqual(x.trail.map(r=>r.answered),[3,3,3,3,3]);assert.deepEqual(x.trail.map(r=>r.reviewDays),[14,30,30,30,30]);assert.equal(x.P.rewardFor({teacherTaskCompleted:true,retention30Passed:true}).points,20)});
